### PR TITLE
Use timer queue instead of SetTimer()

### PR DESCRIPTION
**Pull request by mpaperno**
Hi John,

Tried using the API in a console app, but not much joy because the timers never fired (even with a console window handle, as expected).

This seems to work fine instead.

Thanks for making the sources available, I would have been stuck w/out 'em.  And the WASM module of course also!

Cheers,
-Max

### CODE REVIEW

**Comment by jldowson** [comment]
Hi Max,

I thought it would work with a NULL window handle, but maybe not. I'll review your changes next week and merge them in to the next release if all ok.

Thanks for your input.

`And the WASM module of course also!

The WASM module should also be open source but there are a few changes I've been meaning to do for a while now but just haven't had time. If you would like access to this, let me know and I will grant you permissions.
The main change I would like to do is to remove the gauge event handler and move everything to use the SimConnect event handler, and therefore removing the possible issue with using event ids/numbers possibly already used. 

Cheers,

John

**Comment by mpaperno** [comment]
Thanks John.

Nope, definitely didn't work with null either.  Never even got the "Config data requested..." log message.  I kept comparing to the GUI client example until it finally dawned on me that those timers won't/don't work (known issue actually, lots of SO hits, but of course it's one of those things I never remember until after wasting a bunch of time on it... only to find an "already visited" color link to an SO answer or whatever).

Sure, I'd love to check out what you're working with on the WASM side.  I'm actually looking at integrating with WASM module for [a project](https://github.com/mpaperno/MSFSTouchPortalPlugin) I've been working on, and have been investigating what's out there already.  Really what I need is pretty simple on the WASM side... exec calc code, basically, with optional return values. With extra bonus of acting like SimConnect for requesting value updates with configurable refresh rates and delta epsilon comparisons.

I want to keep the bulk of the data on UI side, like all the zillion possible inputs and output (have you seen www.HubHop.com ? All that data is available via API).   The WASM can provide L var lists of course, which is nice, though again once the data has been discovered once it could be mostly static, I'd think.  And some of the var names coming back are cryptic or useless anyway, like just a long hex string for a name... so ideally they need to be filtered out somehow for users anyway.

More on topic,, I did write a full C++/CLI style C# wrapper for `WASMIF` which I'm happy to share if you're interested... I'll push it to my fork soon,  just need to clean it up a tad and figure out the right name to use... :)

Best,
-Max

**Comment by jldowson** [comment]
Hi Max,

>Nope, definitely didn't work with null either. Never even got the 
>"Config data requested..." log message. I kept comparing to the GUI 
>client example until it finally dawned on me that those timers 
>won't/don't work (known issue actually, lots of SO hits, but of course 
>it's one of those things I never remember until after wasting a bunch 
>of time on it... only to find an "already visited" color link to an SO 
>answer or whatever).
>
>Sure, I'd love to check out what you're working with on the WASM side. 
>I'm actually looking at integrating with WASM module for a project 
><https://github.com/mpaperno/MSFSTouchPortalPlugin> I've been working 
>on, and have been investigating what's out there already. Really what I 
>need is pretty simple on the WASM side... exec calc code, basically, 
>with optional return values. With extra bonus of acting like SimConnect 
>for requesting value updates with configurable refresh rates and delta 
>epsilon comparisons.
>
There is currently no return value available when executing calculator 
code. This is difficult to implement due to the asynchronous nature of 
the Simconnect API. I don't see the need for this either...

>I want to keep the bulk of the data on UI side, like all the zillion 
>possible inputs and output (have you seen www.HubHop.com ? All that 
>data is available via API).
>
Yes, of course. FSUIPC7 includes all the MF presets via the events.txt 
file, and you can also add your own presets using the myevents.txt file. 
All presets are executed as calculator code.

>The WASM can provide L var lists of course, which is nice, though again 
>once the data has been discovered once it could be mostly static, I'd 
>think.
>
Some lvars are created some time after the aircraft has been loaded. 
There is a WASM ini parameter LvarScanDelay that can be used to delay 
the scanning. This is set to 5s by default, but should be increased to 
45s (and above) if using more complex aircraft, such as airliners.
Reloading the WASM will also re-scan for lvars, and a reload is 
automatically performed when you list the lvars (using the WASM-> List 
Lvars menu item).
>And some of the var names coming back are cryptic or useless anyway, 
>like just a long hex string for a name... so ideally they need to be 
>filtered out somehow for users anyway.
>
You can just ignore the lvars you don't need, I don't see any need to 
filter them, unless the max limit of lvars (currently 2044 I think) has 
been reached...
>More on topic,, I did write a full C++/CLI style C# wrapper for WASMIF 
>which I'm happy to share if you're interested... I'll push it to my 
>fork soon, just need to clean it up a tad and figure out the right name 
>to use...
>:)
>
I don't use C# myself, but there is already a C# wrapper to the WAPI, 
provided by Paul Henty's client dll for .Net. This also provides access 
to the FSUIPC SDK, but can be used just for WAPI access (I believe). See 
https://forum.simflight.com/forum/167-fsuipc-client-dll-for-net/
>Message ID: ***@***.***>
>
Regards,

John

**Comment by jldowson** [comment]
By the way, there I also provide a simple wrapper project that is used 
by Paul Henty's .net dll, see https://github.com/jldowson/FSUIPC_WDLL.

John

------ Original Message ------
From: "John Dowson" ***@***.***>
To: "jldowson/FSUIPC_WAPI" 
***@***.***>
Sent: 24/04/2022 13:02:46
Subject: Re[2]: [jldowson/FSUIPC_WAPI] Use timer queue instead of 
SetTimer() (PR #3)

**Comment by mpaperno** [comment]
Hi John,

> There is currently no return value available when executing calculator code.

I'm not sure what you mean... the gauge method can return a value.. then that value can be treated as any other variable, basically, returned with the unique ID it was requested with.  Well, I'm simplifying of course. 

> FSUIPC7 includes all the MF presets via the events.txt file

Right, though the lists are pretty short at the moment. Also only seems to load for default livery versions, though I haven't tested that thoroughly.

> All presets are executed as calculator code.

Well that's pretty much what I'm getting at... for my needs, the UI can be used to select what the user wants to do (eg. from a list updated via HubHop) and then just send the corresponding calc code.  Which is of course already possible via your WASM, and at the moment that's all I'm using, and works fine to activate any imaginable event as well as custom code.  Just no way to get values back right now.  (BTW, the `executeCalculatorCode()` did work fine w/out a window handle, it was just the timers that didn't.)

> Some lvars are created some time after the aircraft has been loaded.

Good to know, thanks!

And yes I've seen the DLL project and Paul's wrapper, but I don't see the need to involve yet another abstraction layer... and the DLL and the wrapper are outdated already (AFAICT, for example, the wrapper is tracking ID-to-name mappings internally instead of using the new by-name accessors directly... and it needs to keep refreshing the vars list constantly).  Oh and it doesn't work in a console app either... and it's not OSS   ;-)

Cheers,
-Max

**Comment by jldowson** [comment]
Hi Max,

>>There is currently no return value available when executing calculator 
>>code.
>>
>I'm not sure what you mean... the gauge method can return a value.. 
>then that value can be treated as any other variable, basically, 
>returned with the unique ID it was requested with. Well, I'm 
>simplifying of course.
>
I mean that there is no return value from executing calculator code via 
the FSUIPC WAPU/WASM.

>>FSUIPC7 includes all the MF presets via the events.txt file
>>
>Right, though the lists are pretty short at the moment.
>
What do you mean by this? There are > 4000 presets currently available. 
The events.txt file included with FSUIPC7 will be slightly out-of-date 
compared to the latest MF events.txt file, vut you can always download 
this and use it to replace the current installed version.
>  Also only seems to load for default livery versions, though I haven't 
>tested that thoroughly.
>
Not sure what you mean by this either...the livery being used should in 
no way affect what presets are loaded. All presets are loaded, 
regardless of aircraft or livery.
>>All presets are executed as calculator code.
>>
>Well that's pretty much what I'm getting at... for my needs, the UI can 
>be used to select what the user wants to do (eg. from a list updated 
>via HubHop) and then just send the corresponding calc code. Which is of 
>course already possible via your WASM, and at the moment that's all I'm 
>using, and works fine to activate any imaginable event as well as 
>custom code. Just no way to get values back right now. (BTW, the 
>executeCalculatorCode() did work fine w/out a window handle, it was 
>just the timers that didn't.)
>
But why do you want values back? Usually the values updated via 
calculator code can be seen in the L:var or A:var changes...
>
>
>>Some lvars are created some time after the aircraft has been loaded.
>>
>Good to know, thanks!
>
>And yes I've seen the DLL project and Paul's wrapper, but I don't see 
>the need to involve yet another abstraction layer... and the DLL and 
>the wrapper are outdated already (AFAICT, for example, the wrapper is 
>tracking ID-to-name mappings internally instead of using the new 
>by-name accessors directly... and it needs to keep refreshing the vars 
>list constantly). Oh and it doesn't work in a console app either... and 
>it's not OSS
>;-)
>
Not sure what  you mean by this... The wrapper tracks nothing - it is 
simply a light-weight wrapper.
And what do you mean by ' it needs to keep refreshing the vars list 
constantly'? Thats not done in the wrapper, but is a feature of the WAPI 
to maintain current values. By default, it refreshes at 6Hz, but can be 
set to refresh at 1Gz, on Frame, VisualFrame or on request.

John

**Comment by jldowson** [comment]
Btw, could it have been that the timers weren't working as you hadn't target your command-line application to windows?
It seems that the current WAPI and wrapper CAN be used with such applications. See https://forum.simflight.com/topic/93717-net-6-support/?do=findComment&comment=571310.

I am also not sure about your second commit:

`> https://github.com/jldowson/FSUIPC_WAPI/commit/cccd8dc8343c7e4b4053e1e6b33f75fb57a3de34  Use an event handle to check for pending SimConnect messages instead of constantly calling SimConnect_CallDispatch(). Increases thread "sleep" time to 500ms (which is actually now an event-or-timeout wait).
`
I will need to check this... SimConnect_CallDispatch is the standard way of processing messages in non-managed code - I've not used an event handler for this before and not sure of the consequences. A thread sleep time of 500ms seems incredibly large. Wouldn't this throttle the lvar update rate?

John
John

**Comment by mpaperno** [comment]
> There are > 4000 presets currently available. The events.txt file included with FSUIPC7

I had no idea there was a newer version, was just using what was included with the WASM module downloaded from your site directly.

What I don't understand is why all those events needs to be loaded on the simulator side at all.  IMHO it is easier to keep a list like that updated on the UI side.  I mean all the events are literally just a calc string which the client can send directly. Maybe I'm missing something, but it works exactly like that right now with `executeCalculatorCode()`... any "input" event from the HubHop database I've tried works fine.

> Not sure what you mean by this either...the livery being used should in no way affect what presets are loaded.

Just saying it didn't work for me, with those old event files anyway. Using your test client, so not my own code. Once I loaded up the same aircraft with default livery, the hvars showed up.

> The wrapper tracks nothing - it is simply a light-weight wrapper.

I was talking about Paul's C# version.  It's not just a lightweight wrapper.

Best,
-Max

**Comment by mpaperno** [comment]
> Btw, could it have been that the timers weren't working as you hadn't target your command-line application to windows?
> It seems that the current WAPI and wrapper CAN be used with such applications. See https://forum.simflight.com/topic/93717-net-6-support/?do=findComment&comment=571310.

That question seems to be referring to a build error. Nothing about it actually working, AFAICT.  In any case in .Net5, which I'm using, there's no such option for a specific target anyway (or maybe they're talking some other kind of project, I have no idea).

Anyway a quick search on SO will show that those timers don't work with console windows.  If .Net 6 has some workaround for that, great.

> A thread sleep time of 500ms seems incredibly large. Wouldn't this throttle the lvar update rate?

It's not a sleep.  It's waiting for the event to be signaled by SimConnect when data becomes available.  As soon as the wait handle is signaled, the dispatch proc is called, no delay at all.

The 500ms is just how long it waits before it times out and repeats the loop, again no delay there.  The only thing this dictates is how long one may have to wait before the loop exits after `quit` is set.

The wait handle is absolutely the way to go, that's exactly what's it's there for.  The managed C# version has the exact same mechanism (which a lot of ppl don't seem to know about). 

-Max

**Comment by jldowson** [comment]
>
>>There are > 4000 presets currently available. The events.txt file 
>>included with FSUIPC7
>>
>I had no idea there was a newer version, was just using what was 
>included with the WASM module downloaded from your site directly.
>
Sorry, I should have been clearer...These are included with FSUIPC7, not 
in the WASM.
>
>
>What I don't understand is why all those events needs to be loaded on 
>the simulator side at all. IMHO it is easier to keep a list like that 
>updated on the UI side. I mean all the events are literally just a calc 
>string which the client can send directly. Maybe I'm missing something, 
>but it works exactly like that right now with 
>executeCalculatorCode()... any "input" event from the HubHop database 
>I've tried works fine.
>
Yes, they are included on the client side, which is FSUIPC7 - if using 
that. Otherwisem if using your own client, it is up to the client to 
handle this.
>>Not sure what you mean by this either...the livery being used should 
>>in no way affect what presets are loaded.
>>
>Just saying it didn't work for me, with those old event files anyway. 
>Using your test client, so not my own code. Once I loaded up the same 
>aircraft with default livery, the hvars showed up.
>
Ok, so you are referring to the loading of hvar files. To use for all 
liveries, you can rename to a substring of the folder name and use the 
WASM ini parameter UseAirLocForHvars. The documentation for the WASM is 
included in the FSUIPC7 Advanced User Guide. Maybe download and install 
FSUIPC7 just to get this document. You can uninstall afterwards if not 
using.

However, there is no need to use hvar files any more really, as you can 
just activate them via calculator code.

John

**Comment by mpaperno** [comment]
> Yes, they are included on the client side, which is FSUIPC7 - if using that.

Ah OK, so we're on the same page on that then, cool. That's what I'm doing on my UI side now. And yea sorry, don't now much about FSUIPC except a few add-ons I've tried used it.  Actually still have it installed, so I'll check what you mean there.

And right, no need for the hvar files and getting them from WASM module.  👍🏼 

Cheers,
-Max

**Pull request merged**
